[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
fuzzy-matcher = "0.3.7"
git2 = "0.19.0"
glob = "0.3.1"
hostname = "0.4.0"
itertools = "0.13.0"
nix = { version = "0.29.0", features = ["process", "fs"] }
nom = "7.1.3"
termion = "4.0.3"
